spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/research_db
spring.datasource.username=postgres
spring.datasource.password=Star123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true